# action.yml
name: 'Build Journal'
description: 'Build Journal'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - make
